layout_spectrum: 1
color:
  saturation: 0
  brandStrength: 0.6689291
  lightness: 0.7893617
  rhythmicContrast: 0.1489362
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
typography_spectrum: 1
name: Between The Commons
